### PR TITLE
Add integrated reaction rates and plots

### PR DESCRIPTION
**Pull request by s-omas**

### CODE REVIEW

**Review by AndrewJConley — COMMENTED** [review]
I'm a little confused by the notation of these being "CONC.myrate__".

When I output the data for analysis, I'd prefer if the label were something like "IRR.myrate__" 

I'd like to discuss this further.

**Comment by mattldawson** [comment]
That's a side effect of doing this solely in the interface (not in the box model). The box model treats the integrated reaction rates as a species, and outputs its value with the `CONC.` prefix

**Comment by s-omas** [comment]
I might be able to edit the column names of the csv file in the interface to be something like "IRR."

**Review by mattldawson — APPROVED** [review]
works great! I think at some point we want to have a toggle in the general conditions to turn on/off the calculation of the integrated rates, but this can be added later

**Pull request merged**
